# Generated by Django 3.2.8 on 2022-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipie',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipie', to='book.Ingredients'),
        ),
    ]
