# Generated by Django 3.2.8 on 2022-02-22 04:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='instruction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
