version: '3.7'

services:

  # Database
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433


  # The application
  app:
    build:
      context: .
    image: &app app
    ports:
      - 8000:8000
    volumes:
      - ./recepie_book:/book
    env_file:
      - .env
    command: >
      sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py loaddata book/fixtures/initial_data2.json
      && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py runserver --settings=config.settings.production 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db